### ISSUE TITLE
Some settings are out of range for the LN1301.

### ISSUE THREAD

**Issue by famewolf** [arix00/openwrt-mx4300#49]
### Describe the bug

It appears 160mhz is unavailable to the LN1301 but is a menu choice.  Additionally the high band of 5GHZ wifi supports channels from 149-169 but the "auto" settings allows for 140-148 and some channels on the high end also.  These don't work.  This info came from https://www.reddit.com/r/openwrt/comments/1fgta78/comment/lqwp0er/

### OpenWrt version

OpenWrt SNAPSHOT r28217-af611bce44 / LuCI Master 24.335.53348~98c0413

### OpenWrt release

OpenWrt SNAPSHOT r28217-af611bce44 / LuCI Master 24.335.53348~98c0413

### OpenWrt target/subtarget

OpenWrt SNAPSHOT r28217-af611bce44 / LuCI Master 24.335.53348~98c0413

### Device

Linksys LN1301

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
Please understand this repo is for building, these issues are mostly on upstream.

1. 160MHz is a problem I don't know where luci gets the value but `iw list` shows 160MHz as valid value. Please report it to openwrt.

2. Other channels are DFS, they're good and working in MX4300. Set country code to "US" instead of "driver default", also the client need to have proper region settings -- can be a problem for some android -- to connect to DFS.

**Comment by famewolf** [comment]
Thank you for the clarification. Sorry for the bother.
